### ISSUE TITLE
Favorites popup doesn't show all favorites (cropped)

### ISSUE THREAD

**Issue by lvernaillen** [thdk/team-timesheets#204]
Clicking the + item to add a favorite registration brings up a list of favorites.
However, that list is not complete. It is cropped and items at the bottom are not visible.

![image](https://user-images.githubusercontent.com/4180374/106477606-9dd1fc80-64a8-11eb-823e-c84bdbc7bdb5.png)

**Comment by lvernaillen** [comment]
Hmm, had it several times.
Added a manual registration and is ok again now.
Can't reproduce...

**Comment by thdk** [comment]
You can easyly reproduce it if you try it on an empty day (day without any registrations yet)
A fix is on the way! :)
