### ISSUE TITLE
Can link to jira open in new tab?

### ISSUE THREAD

**Issue by vanrumstf** [thdk/team-timesheets#273]
Atm it opens in same tab when clicking on link.
Or maybe add option in profile to let everyone chose for himself if he wants to open links in new tab or not.

**Comment by thdk** [comment]
@vanrumstf can you click the to jira while pressing `ctrl` or `shift`? That should open the link in new tab or new window. A developer should not interfere with this behavior and most browser actually don't even allow you to do so.

**Comment by vanrumstf** [comment]
This works!
