### ISSUE TITLE
Error when making Jira connection with 2 word username

### ISSUE THREAD

**Issue by brabantjonas** [thdk/team-timesheets#286]
When adding the Jira connection, using a Jira username made out of 2 words seperated using a space character, the connection fails.
This results in a bigger fail, which is the timesheets pages fails to load.

The only way to solve the issue at this moment is to go to [this link](https://express-timesheets.firebaseapp.com/profile?tab=connections) and delete the Jira settings.

**Comment by thdk** [comment]
This has been solved by editing the jira query to wrap user names with quotes.
However, a jql formatting issue should never crash the app which is solved here 1ab7f31bf1eaed090118fe0362e1f37185253f3f
