### ISSUE TITLE
Add more colours to Dashboard

### ISSUE THREAD

**Issue by ArneFigoureux** [thdk/team-timesheets#288]
Currently only 6 or so colours are being used to represent the different tasks, other tasks are being shown in black.

**Comment by thdk** [comment]
@ArneFigoureux feel free the submit a PR! :)

See here for related code: https://github.com/thdk/team-timesheets/blob/88f8b3a1f7e6ed0a5d7cda5dd9f076fdc3c73293/src/containers/timesheet/chart/index.tsx#L14
